name: dept
channels:
  - conda-forge
  - defaults
dependencies:
  # base
  - python=3.10
  - pandas=2.1.4
  - numpy=1.26.2
  - openpyxl=3.1.2
  - XlsxWriter=3.2.0

  # APIs
  - requests=2.31.0

  # jupyter
  - ipykernel=6.28.0

  # aws
  - boto3=1.34.8

  # databases
  - sqlalchemy=2.0.29
  - psycopg2=2.9.9