name: dept
channels:
  - conda-forge
  - defaults
dependencies:
  # base
  - python=3.10
  - pandas=2.1.4
  - numpy=1.26.2

  # APIs
  - requests=2.31.0

  # jupyter
  - ipykernel=6.28.0

  # aws
  - boto3=1.34.8


